### ISSUE TITLE
Build error on bare system - building from source

### ISSUE THREAD

**Issue by ratnadeepb** [capsule-rs/capsule#119] opened 2021-01-20 16:52 UTC
## Describe the bug?

Trying to build the repo from source throws errors about SSE support. Here is the error in its entirety:

## Steps to reproduce?
1. git clone https://github.com/capsule-rs/capsule.git
2. cargo build

## Expected behavior?

Successful build

### Capsule version?

Git

### OS?

Ubuntu 18.10

### Docker / VM / Bare?

Bare

### Stack trace or error log output

`  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-march=corei7" "-o" "/users/deep83/rust/capsule/target/debug/build/capsule-ffi-9f389138f8a5f94a/out/src/shim.o" "-c" "src/shim.c"
  cargo:warning=In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:41:0,
  cargo:warning=                 from /usr/lib/gcc/x86_64-linux-gnu/7/include/x86intrin.h:48,
  cargo:warning=                 from /usr/local/include/rte_vect.h:28,
  cargo:warning=                 from /usr/local/include/rte_memcpy.h:17,
  cargo:warning=                 from /usr/local/include/rte_ether.h:21,
  cargo:warning=                 from /usr/local/include/rte_ethdev.h:159,
  cargo:warning=                 from src/shim.c:20:
  cargo:warning=/usr/local/include/rte_memcpy.h: In function ‘rte_mov32’:
  cargo:warning=/usr/lib/gcc/x86_64-linux-gnu/7/include/avxintrin.h:926:1: error: inlining failed in call to always_inline ‘_mm256_storeu_si256’: target specific option mismatch
  cargo:warning= _mm256_storeu_si256 (__m256i_u *__P, __m256i __A)
  cargo:warning= ^~~~~~~~~~~~~~~~~~~
  cargo:warning=In file included from /usr/local/include/rte_ether.h:21:0,
  cargo:warning=                 from /usr/local/include/rte_ethdev.h:159,
  cargo:warning=                 from src/shim.c:20:
  cargo:warning=/usr/local/include/rte_memcpy.h:321:2: note: called from here
  cargo:warning=  _mm256_storeu_si256((__m256i *)dst, ymm0);
  cargo:warning=  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  cargo:warning=In file included from /usr/lib/gcc/x86_64-linux-gnu/7/include/immintrin.h:41:0,
  cargo:warning=                 from /usr/lib/gcc/x86_64-linux-gnu/7/include/x86intrin.h:48,
  cargo:warning=                 from /usr/local/include/rte_vect.h:28,
  cargo:warning=                 from /usr/local/include/rte_memcpy.h:17,
  cargo:warning=                 from /usr/local/include/rte_ether.h:21,
  cargo:warning=                 from /usr/local/include/rte_ethdev.h:159,
  cargo:warning=                 from src/shim.c:20:
  cargo:warning=/usr/lib/gcc/x86_64-linux-gnu/7/include/avxintrin.h:920:1: error: inlining failed in call to always_inline ‘_mm256_loadu_si256’: target specific option mismatch
  cargo:warning= _mm256_loadu_si256 (__m256i_u const *__P)
  cargo:warning= ^~~~~~~~~~~~~~~~~~
  cargo:warning=In file included from /usr/local/include/rte_ether.h:21:0,
  cargo:warning=                 from /usr/local/include/rte_ethdev.h:159,
  cargo:warning=                 from src/shim.c:20:
  cargo:warning=/usr/local/include/rte_memcpy.h:320:7: note: called from here
  cargo:warning=  ymm0 = _mm256_loadu_si256((const __m256i *)src);
  cargo:warning=  ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  exit code: 1

  --- stderr

  error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-march=corei7" "-o" "/users/deep83/rust/capsule/target/debug/build/capsule-ffi-9f389138f8a5f94a/out/src/shim.o" "-c" "src/shim.c" with args "cc" did not execute successfully (status code exit code: 1).`

**Comment by zeeshanlakhani** [comment] 2021-01-23 17:13
If you're building without docker or our vm (via vagrant), take a gander here: https://github.com/capsule-rs/sandbox#without-docker. You'll need to install dpdk, etc...

**Comment by ratnadeepb** [comment] 2021-01-23 19:35
@zeeshanlakhani actually I have been working on something similar. I have been using a slightly modified version of your `ffi` crate and `core/dpdk` module. I can build things fine. But when I try to build this repo from source it throws me this error.

Pre-requisites wise, I have the following libs installed - `build-essential linux-headers-$(uname -r) git libnuma-dev linux-modules-extra-$(uname -r) libclang-dev clang llvm-dev libpcap-dev dpdk-igb-uio-dkms ninja-build`. I am building DPDK with `meson 0.56` and `ninja 1.8.2`. The `igb_uio` driver is from `dpdk.org/dpdk-kmods`.

That's what confuses me. The build scrip I use is mostly a derivative of the one you have. And for the `bindings.h` and `shim.c`, I have only added to those.

Also, I am building these on cloudlab's Ubuntu18 machines (if that helps).

**Comment by ratnadeepb** [comment] 2021-01-23 19:38
This is how my `build.rs` stands, in case that helps: https://github.com/ratnadeepb/vdataplane/blob/master/dpdk-sys/build.rs

**Comment by zeeshanlakhani** [comment] 2021-01-23 20:22
@ratnadeepb I'll run up things on my Ubuntu box tonight and see. What DPDK version? Capsule uses 19.11.1 and that matters due to API breakage in previous version. It seems specifically an issue in loading rte_ethdev, which we do here: https://github.com/capsule-rs/capsule/blob/master/ffi/build.rs#L47

**Comment by ratnadeepb** [comment] 2021-01-23 20:49
This error is from DPDK 19.11.6.

**Comment by zeeshanlakhani** [comment] 2021-01-23 21:20
@ratnadeepb ill test on that version this evening and see. I’ll be using our dpdk and setup install scripts [here](https://github.com/capsule-rs/sandbox/tree/master/scripts).

**Comment by zeeshanlakhani** [comment] 2021-01-23 22:58
@ratnadeepb I was able to reproduce and fix. I'll push up a PR for @drunkirishcoder to test/review as well. 

I repro'ed on 19.11.1, but will move us to 19.11.6 for LTS as part of this too. 

We'll prob ship an ffi cargo release sometime later this week (possibly with a couple small changes, like moving to rust 1.49 too).

**Comment by ratnadeepb** [comment] 2021-01-24 01:40
@zeeshanlakhani cool!

**Closed** 2021-01-27 18:35 UTC
Labels: bug
